### ISSUE TITLE
Does not autofill @class which prevents Doxygen from showing the @brief for the class

### ISSUE THREAD

**Issue by coreydaley** [cschlosser/doxdocgen#197]
# Description

DoxDocGen should automatically add the @class into the file header for cpp and fill it with the main class for that file.
When @class is not present, the @brief is not included when running Doxygen.

**Comment by cschlosser** [comment]
Filling the name of the main class is probably not trivial.
Adding the `@class` attribute should be fairly easy for C++.

Probably could be solved with #191 

> When @Class is not present, the @brief is not included when running Doxygen.

Do you have a file and config to reproduce this? It works for me just fine without the `@class`

**Comment by coreydaley** [comment]
I have a partial pull request, just having an issue getting the class name (as you mentioned).
I don't think it's getting parsed into the list of tokens.

**Comment by cschlosser** [comment]
No it's not.
Since the parser is not really context aware but instead token/string based and doesn't really know about C/C++ on a language level like through a compilation database.
With macros, namespaces and all the other shenanigans it would be nearly impossible to determine the class name for a file. There are also quite a few additional unsolved questions e.g.: What if there are several classes in one file (pimpl)?
