### ISSUE TITLE
[feature request] add "@" before all doxygen command snippets' names

### ISSUE THREAD

**Issue by NewtMa** [cschlosser/doxdocgen#224]
# Description

First of all, thank you for continuous effort to make us developers' life easier.

I'm using C++ and C++ extension has its own snippets, and the doxygen command snippets could mixed up.

The picture below is an example.

![image](https://user-images.githubusercontent.com/48610536/117925697-2c68dc00-b32a-11eb-9784-3c26b5669a3a.png)

I would suggest to add a "@" before all doxygen command snippets name, so that whenever I type "if" those doxygen snippets won't show.

**Comment by HO-COOH** [comment]
After #229 is merged, doxygen command should no longer appearing in normal code. But it could still appear in strings where `*` exists, due to the limit of parser. (But I think it's reasonably close enough 😄 )

Also, you can enable the settings to add a `\` as prefix for better distinguishability.
![](https://user-images.githubusercontent.com/42881734/118384718-136a6e80-b63b-11eb-8ce3-8c8ee7485a93.png)

**Comment by NewtMa** [comment]
@HO-COOH Hi, which setting are you talking about?

**Comment by HO-COOH** [comment]
There ~~will be~~ is `"doxdocgen.generic.commandSuggestionAddPrefix": true`
